// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: DataPad

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void PowerUpAll(lv_event_t * e);
void SyncModeToggle(lv_event_t * e);
void TouchSoundToggle(lv_event_t * e);
void AmbientToggle(lv_event_t * e);
void NavLightsSet(lv_event_t * e);
void ImpulsEng(lv_event_t * e);
void DamageControl(lv_event_t * e);
void NacelleToggle(lv_event_t * e);
void DeflectorToggle(lv_event_t * e);
void WarpSpeed(lv_event_t * e);
void WarpCoreToggle(lv_event_t * e);
void RadarToggle(lv_event_t * e);
void RadarAlertToggle(lv_event_t * e);
void WindowsToggle(lv_event_t * e);
void RedAlertStart(lv_event_t * e);
void RedAlertDismiss(lv_event_t * e);
void YellowAlertStart(lv_event_t * e);
void YellowAlertDismiss(lv_event_t * e);
void AllOff(lv_event_t * e);
void AllOn(lv_event_t * e);
void PhotonFire(lv_event_t * e);
void BridgeAssemblyMode(lv_event_t * e);
void EngRoomAssemblyMode(lv_event_t * e);
void StartWiFi(lv_event_t * e);
void SaveWifi(lv_event_t * e);
void PadAudioDest(lv_event_t * e);
void PadVolume(lv_event_t * e);
void BridgeVolume(lv_event_t * e);
void EasterEggFunny(lv_event_t * e);
void EasterEggStarWars(lv_event_t * e);

extern lv_obj_t * ui_DeflectorLabel;
extern bool touchSoundEnabled;
extern bool ambientEnabled;
void play_touch_sound(void);
void populateWifiFields(void);
extern uint8_t padSndVol;
extern uint8_t bridgeSndVol;
extern int     nvsSyncMode;
extern bool    warpCoreOn;
extern bool    radarEnabled;
extern bool    redAlertSensorEnabled;
extern bool    redAlertActive;
extern bool    windowsOn;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
