// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: DataPad

#ifndef UI_SCREEN3_H
#define UI_SCREEN3_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen3
extern void ui_Screen3_screen_init(void);
extern void ui_Screen3_screen_destroy(void);
extern lv_obj_t * ui_Screen3;
extern lv_obj_t * ui_Keyboard1;
extern void ui_event_TextArea1(lv_event_t * e);
extern lv_obj_t * ui_TextArea1;
extern void ui_event_TextArea2(lv_event_t * e);
extern lv_obj_t * ui_TextArea2;
extern void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern void ui_event_Label12(lv_event_t * e);
extern lv_obj_t * ui_Label12;
extern void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern void ui_event_Label1(lv_event_t * e);
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Button45;
extern void ui_event_Label16(lv_event_t * e);
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_Button46;
extern void ui_event_Label17(lv_event_t * e);
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_Button47;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_Label22;
extern void ui_event_Button50(lv_event_t * e);
extern lv_obj_t * ui_Button50;
extern void ui_event_Label25(lv_event_t * e);
extern lv_obj_t * ui_Label25;
extern lv_obj_t * ui_WarpCoreStsBtn;
extern lv_obj_t * ui_LabelWCIP;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

