// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: DataPad

#include "ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_Button33 = NULL;
lv_obj_t * ui_Button44 = NULL;
lv_obj_t * ui_Button39 = NULL;
lv_obj_t * ui_Button40 = NULL;
lv_obj_t * ui_Button41 = NULL;
lv_obj_t * ui_Button38 = NULL;
lv_obj_t * ui_Button37 = NULL;
lv_obj_t * ui_Button36 = NULL;
lv_obj_t * ui_Button35 = NULL;
lv_obj_t * ui_Button34 = NULL;
lv_obj_t * ui_Button32 = NULL;
lv_obj_t * ui_Button31 = NULL;
lv_obj_t * ui_Label10 = NULL;
lv_obj_t * ui_Button30 = NULL;
lv_obj_t * ui_Button13 = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_Button14 = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_Button15 = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_Button16 = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_Button17 = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_Button42 = NULL;
lv_obj_t * ui_Button43 = NULL;
lv_obj_t * ui_Label8 = NULL;
lv_obj_t * ui_Button48 = NULL;
lv_obj_t * ui_Label23 = NULL;
lv_obj_t * ui_Button49 = NULL;
lv_obj_t * ui_Label24 = NULL;
lv_obj_t * ui_Button51 = NULL;
lv_obj_t * ui_Label26 = NULL;
lv_obj_t * ui_DeflectorBtn   = NULL;
lv_obj_t * ui_DeflectorLabel = NULL;
lv_obj_t * ui_WarpSlider     = NULL;
lv_obj_t * ui_RedAlertBtn    = NULL;
lv_obj_t * ui_YellowAlertBtn = NULL;
// event funtions
void ui_event_RedAlertBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_CLICKED) {
        play_touch_sound();
        RedAlertStart(e);
    }
}

void ui_event_YellowAlertBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_CLICKED) {
        play_touch_sound();
        YellowAlertStart(e);
    }
}

void ui_event_WarpSlider(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        WarpSpeed(e);
    }
}

void ui_event_DeflectorBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_CLICKED) {
        play_touch_sound();
        DeflectorToggle(e);
    }
}

void ui_event_Button13(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        play_touch_sound();
        PowerUpAll(e);
    }
}

void ui_event_Button16(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        play_touch_sound();
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen2_screen_init);
    }
}

void ui_event_Button17(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        play_touch_sound();
        NavLightsSet(e);
    }
}

void ui_event_Button48(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        play_touch_sound();
        ImpulsEng(e);
    }
}

void ui_event_Button49(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        play_touch_sound();
        DamageControl(e);
    }
}

void ui_event_Button14(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        play_touch_sound();
        NacelleToggle(e);
    }
}

void ui_event_Button15(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        play_touch_sound();
        PhotonFire(e);
    }
}

void ui_event_Button51(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        play_touch_sound();
        _ui_screen_change(&ui_BridgeSound, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_BridgeSound_screen_init);
    }
}

void ui_event_Button38(lv_event_t * e)
{
    if (lv_event_get_code(e) == LV_EVENT_CLICKED) EasterEggFunny(e);
}

void ui_event_Button35(lv_event_t * e)
{
    if (lv_event_get_code(e) == LV_EVENT_CLICKED) EasterEggStarWars(e);
}

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button33 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button33, 132);
    lv_obj_set_height(ui_Button33, 147);
    lv_obj_set_x(ui_Button33, -317);
    lv_obj_set_y(ui_Button33, -124);
    lv_obj_set_align(ui_Button33, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button33, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button33, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_obj_set_style_radius(ui_Button33, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button33, lv_color_hex(0xCC99FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button33, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button44 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button44, 87);
    lv_obj_set_height(ui_Button44, 36);
    lv_obj_set_x(ui_Button44, -340);
    lv_obj_set_y(ui_Button44, 60);
    lv_obj_set_align(ui_Button44, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button44, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button44, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_obj_set_style_radius(ui_Button44, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button44, lv_color_hex(0xFF9966), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button44, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button39 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button39, 91);
    lv_obj_set_height(ui_Button39, 100);
    lv_obj_set_x(ui_Button39, -251);
    lv_obj_set_y(ui_Button39, -56);
    lv_obj_set_align(ui_Button39, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button39, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button39, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_obj_set_style_radius(ui_Button39, 700, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button39, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button39, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button40 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button40, 91);
    lv_obj_set_height(ui_Button40, 84);
    lv_obj_set_x(ui_Button40, -250);
    lv_obj_set_y(ui_Button40, -197);
    lv_obj_set_align(ui_Button40, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button40, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button40, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_obj_set_style_radius(ui_Button40, 700, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button40, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button40, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button41 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button41, 27);
    lv_obj_set_height(ui_Button41, 49);
    lv_obj_set_x(ui_Button41, 151);
    lv_obj_set_y(ui_Button41, -131);
    lv_obj_set_align(ui_Button41, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button41, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button41, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_obj_set_style_radius(ui_Button41, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button41, lv_color_hex(0x8899FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button41, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button38 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button38, 87);
    lv_obj_set_height(ui_Button38, 32);
    lv_obj_set_x(ui_Button38, -340);
    lv_obj_set_y(ui_Button38, -218);
    lv_obj_set_align(ui_Button38, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button38, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button38, LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_obj_set_style_radius(ui_Button38, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button38, lv_color_hex(0xCC99FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button38, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button37 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button37, 87);
    lv_obj_set_height(ui_Button37, 22);
    lv_obj_set_x(ui_Button37, -340);
    lv_obj_set_y(ui_Button37, 137);
    lv_obj_set_align(ui_Button37, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button37, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button37, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_obj_set_style_radius(ui_Button37, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button37, lv_color_hex(0xFF9966), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button37, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button36 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button36, 87);
    lv_obj_set_height(ui_Button36, 36);
    lv_obj_set_x(ui_Button36, -340);
    lv_obj_set_y(ui_Button36, 102);
    lv_obj_set_align(ui_Button36, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button36, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button36, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_obj_set_style_radius(ui_Button36, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button36, lv_color_hex(0xFF9966), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button36, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button35 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button35, 87);
    lv_obj_set_height(ui_Button35, 80);
    lv_obj_set_x(ui_Button35, -340);
    lv_obj_set_y(ui_Button35, 195);
    lv_obj_set_align(ui_Button35, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button35, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button35, LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_obj_set_style_radius(ui_Button35, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button35, lv_color_hex(0xFF9966), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button35, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button34 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button34, 87);
    lv_obj_set_height(ui_Button34, 82);
    lv_obj_set_x(ui_Button34, -340);
    lv_obj_set_y(ui_Button34, -4);
    lv_obj_set_align(ui_Button34, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button34, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button34, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_obj_set_style_radius(ui_Button34, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button34, lv_color_hex(0xCC99FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button34, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button32 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button32, 77);
    lv_obj_set_height(ui_Button32, 49);
    lv_obj_set_x(ui_Button32, 76);
    lv_obj_set_y(ui_Button32, -131);
    lv_obj_set_align(ui_Button32, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button32, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button32, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_obj_set_style_radius(ui_Button32, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button32, lv_color_hex(0xFFBBAA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button32, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button31 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button31, 261);
    lv_obj_set_height(ui_Button31, 49);
    lv_obj_set_x(ui_Button31, -116);
    lv_obj_set_y(ui_Button31, -131);
    lv_obj_set_align(ui_Button31, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button31, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button31, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_obj_set_style_radius(ui_Button31, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button31, lv_color_hex(0xCC99FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button31, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10 = lv_label_create(ui_Button31);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, 0);
    lv_obj_set_y(ui_Label10, 13);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "USS ENTERPRISE NCC-1701-D");
    lv_obj_set_style_text_color(ui_Label10, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label10, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button30 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button30, 220);
    lv_obj_set_height(ui_Button30, 49);
    lv_obj_set_x(ui_Button30, 280);
    lv_obj_set_y(ui_Button30, -131);
    lv_obj_set_align(ui_Button30, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button30, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button30, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_obj_set_style_radius(ui_Button30, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button30, lv_color_hex(0x8899FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button30, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button13 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button13, 105);
    lv_obj_set_height(ui_Button13, 45);
    lv_obj_set_x(ui_Button13, -199);
    lv_obj_set_y(ui_Button13, -32);
    lv_obj_set_align(ui_Button13, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button13, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button13, 700, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button13, lv_color_hex(0xFFFFAA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_Button13);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 3);
    lv_obj_set_y(ui_Label2, 6);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Power");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button14 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button14, 105);
    lv_obj_set_height(ui_Button14, 45);
    lv_obj_set_x(ui_Button14, -200);
    lv_obj_set_y(ui_Button14, 87);
    lv_obj_set_align(ui_Button14, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button14, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button14, 700, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button14, lv_color_hex(0xFF9C00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_Button14);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, 0);
    lv_obj_set_y(ui_Label5, 7);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "Nacelles");
    lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button15 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button15, 105);
    lv_obj_set_height(ui_Button15, 45);
    lv_obj_set_x(ui_Button15, 90);
    lv_obj_set_y(ui_Button15, 33);
    lv_obj_set_align(ui_Button15, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button15, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button15, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button15, 700, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_Button15);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, 1);
    lv_obj_set_y(ui_Label6, 5);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "Photons");
    lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button16 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button16, 105);
    lv_obj_set_height(ui_Button16, 45);
    lv_obj_set_x(ui_Button16, -64);
    lv_obj_set_y(ui_Button16, 165);
    lv_obj_set_align(ui_Button16, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button16, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button16, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button16, 700, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button16, lv_color_hex(0xFFFFAA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_Button16);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, 0);
    lv_obj_set_y(ui_Label4, 7);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "Settings");
    lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button17 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button17, 105);
    lv_obj_set_height(ui_Button17, 45);
    lv_obj_set_x(ui_Button17, -67);
    lv_obj_set_y(ui_Button17, 33);
    lv_obj_set_align(ui_Button17, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button17, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button17, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button17, 700, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button17, lv_color_hex(0xCC99CC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_Button17);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -3);
    lv_obj_set_y(ui_Label3, 8);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Nav Lights");
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button42 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button42, 13);
    lv_obj_set_height(ui_Button42, 49);
    lv_obj_set_x(ui_Button42, 126);
    lv_obj_set_y(ui_Button42, -131);
    lv_obj_set_align(ui_Button42, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button42, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button42, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_obj_set_style_radius(ui_Button42, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button42, lv_color_hex(0xFFBBAA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button42, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button43 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button43, 13);
    lv_obj_set_height(ui_Button43, 49);
    lv_obj_set_x(ui_Button43, 26);
    lv_obj_set_y(ui_Button43, -131);
    lv_obj_set_align(ui_Button43, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button43, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button43, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_obj_set_style_radius(ui_Button43, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button43, lv_color_hex(0xFFBBAA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button43, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, 203);
    lv_obj_set_y(ui_Label8, -200);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "SYSTEM OFFLINE");
    lv_obj_set_style_text_color(ui_Label8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label8, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Label8, lv_color_hex(0xFF9C00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Label8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button48 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button48, 105);
    lv_obj_set_height(ui_Button48, 45);
    lv_obj_set_x(ui_Button48, 85);
    lv_obj_set_y(ui_Button48, -38);
    lv_obj_set_align(ui_Button48, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button48, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button48, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button48, 700, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button48, lv_color_hex(0xCC99CC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button48, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label23 = lv_label_create(ui_Button48);
    lv_obj_set_width(ui_Label23, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label23, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label23, 1);
    lv_obj_set_y(ui_Label23, 5);
    lv_obj_set_align(ui_Label23, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label23, "Impulse Eng");
    lv_obj_set_style_text_color(ui_Label23, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label23, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label23, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button49 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button49, 105);
    lv_obj_set_height(ui_Button49, 45);
    lv_obj_set_x(ui_Button49, 88);
    lv_obj_set_y(ui_Button49, 100);
    lv_obj_set_align(ui_Button49, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button49, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button49, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button49, 700, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button49, lv_color_hex(0xFFBBAA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button49, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label24 = lv_label_create(ui_Button49);
    lv_obj_set_width(ui_Label24, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label24, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label24, 1);
    lv_obj_set_y(ui_Label24, 5);
    lv_obj_set_align(ui_Label24, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label24, "Damage\nControl");
    lv_obj_set_style_text_color(ui_Label24, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label24, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label24, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button51 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button51, 105);
    lv_obj_set_height(ui_Button51, 45);
    lv_obj_set_x(ui_Button51, -200);
    lv_obj_set_y(ui_Button51, 165);
    lv_obj_set_align(ui_Button51, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button51, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button51, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button51, 700, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button51, lv_color_hex(0xCC99CC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button51, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label26 = lv_label_create(ui_Button51);
    lv_obj_set_width(ui_Label26, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label26, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label26, -3);
    lv_obj_set_y(ui_Label26, 8);
    lv_obj_set_align(ui_Label26, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label26, "Bridge Sound");
    lv_obj_set_style_text_color(ui_Label26, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label26, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label26, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    // ── Deflector toggle button ───────────────────────────────────────────────────
    ui_DeflectorBtn = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_DeflectorBtn, 105);
    lv_obj_set_height(ui_DeflectorBtn, 45);
    lv_obj_set_x(ui_DeflectorBtn, 230);
    lv_obj_set_y(ui_DeflectorBtn, -39);
    lv_obj_set_align(ui_DeflectorBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DeflectorBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);
    lv_obj_clear_flag(ui_DeflectorBtn, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_radius(ui_DeflectorBtn, 700, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_DeflectorBtn, lv_color_hex(0xFF9C00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DeflectorBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DeflectorLabel = lv_label_create(ui_DeflectorBtn);
    lv_obj_set_align(ui_DeflectorLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DeflectorLabel, "DEFLECTOR");
    lv_obj_set_style_text_color(ui_DeflectorLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DeflectorLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DeflectorLabel, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button13, ui_event_Button13, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button14, ui_event_Button14, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button15, ui_event_Button15, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button16, ui_event_Button16, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button17, ui_event_Button17, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button48, ui_event_Button48, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button49, ui_event_Button49, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button51, ui_event_Button51, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DeflectorBtn, ui_event_DeflectorBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button38, ui_event_Button38, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button35, ui_event_Button35, LV_EVENT_ALL, NULL);

    // ── Warp speed slider — vertical, right side ─────────────────────────────────
    ui_WarpSlider = lv_slider_create(ui_Screen1);
    lv_slider_set_range(ui_WarpSlider, 0, 10);
    lv_slider_set_value(ui_WarpSlider, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_WarpSlider, 20);
    lv_obj_set_height(ui_WarpSlider, 220);
    lv_obj_set_x(ui_WarpSlider, 320);
    lv_obj_set_y(ui_WarpSlider, 55);
    lv_obj_set_align(ui_WarpSlider, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_WarpSlider, lv_color_hex(0x444444), LV_PART_MAIN      | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_WarpSlider, lv_color_hex(0xFF9C00), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_WarpSlider, lv_color_hex(0xFF9C00), LV_PART_KNOB      | LV_STATE_DEFAULT);
    lv_obj_add_event_cb(ui_WarpSlider, ui_event_WarpSlider, LV_EVENT_ALL, NULL);

    lv_obj_t * ui_WarpLabel = lv_label_create(ui_Screen1);
    lv_obj_set_x(ui_WarpLabel, 320);
    lv_obj_set_y(ui_WarpLabel, 190);
    lv_obj_set_align(ui_WarpLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WarpLabel, "WARP");
    lv_obj_set_style_text_color(ui_WarpLabel, lv_color_hex(0xFF9C00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WarpLabel, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    // ── Yellow Alert button ───────────────────────────────────────────────────────
    ui_YellowAlertBtn = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_YellowAlertBtn, 105);
    lv_obj_set_height(ui_YellowAlertBtn, 45);
    lv_obj_set_x(ui_YellowAlertBtn, 225);
    lv_obj_set_y(ui_YellowAlertBtn, 117);
    lv_obj_set_align(ui_YellowAlertBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_YellowAlertBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);
    lv_obj_clear_flag(ui_YellowAlertBtn, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_radius(ui_YellowAlertBtn, 700, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_YellowAlertBtn, lv_color_hex(0xFF9C00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_YellowAlertBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * ui_YellowAlertLbl = lv_label_create(ui_YellowAlertBtn);
    lv_obj_set_align(ui_YellowAlertLbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_YellowAlertLbl, "YELLOW\nALERT");
    lv_obj_set_style_text_color(ui_YellowAlertLbl, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_YellowAlertLbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_YellowAlertLbl, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_YellowAlertBtn, ui_event_YellowAlertBtn, LV_EVENT_ALL, NULL);

    // ── Red Alert button ──────────────────────────────────────────────────────────
    ui_RedAlertBtn = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_RedAlertBtn, 105);
    lv_obj_set_height(ui_RedAlertBtn, 45);
    lv_obj_set_x(ui_RedAlertBtn, 225);
    lv_obj_set_y(ui_RedAlertBtn, 168);
    lv_obj_set_align(ui_RedAlertBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_RedAlertBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);
    lv_obj_clear_flag(ui_RedAlertBtn, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_radius(ui_RedAlertBtn, 700, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RedAlertBtn, lv_color_hex(0xCC0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RedAlertBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * ui_RedAlertLbl = lv_label_create(ui_RedAlertBtn);
    lv_obj_set_align(ui_RedAlertLbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RedAlertLbl, "RED\nALERT");
    lv_obj_set_style_text_color(ui_RedAlertLbl, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RedAlertLbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RedAlertLbl, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_RedAlertBtn, ui_event_RedAlertBtn, LV_EVENT_ALL, NULL);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_Button33 = NULL;
    ui_Button44 = NULL;
    ui_Button39 = NULL;
    ui_Button40 = NULL;
    ui_Button41 = NULL;
    ui_Button38 = NULL;
    ui_Button37 = NULL;
    ui_Button36 = NULL;
    ui_Button35 = NULL;
    ui_Button34 = NULL;
    ui_Button32 = NULL;
    ui_Button31 = NULL;
    ui_Label10 = NULL;
    ui_Button30 = NULL;
    ui_Button13 = NULL;
    ui_Label2 = NULL;
    ui_Button14 = NULL;
    ui_Label5 = NULL;
    ui_Button15 = NULL;
    ui_Label6 = NULL;
    ui_Button16 = NULL;
    ui_Label4 = NULL;
    ui_Button17 = NULL;
    ui_Label3 = NULL;
    ui_Button42 = NULL;
    ui_Button43 = NULL;
    ui_Label8 = NULL;
    ui_Button48 = NULL;
    ui_Label23 = NULL;
    ui_Button49 = NULL;
    ui_Label24 = NULL;
    ui_Button51 = NULL;
    ui_Label26 = NULL;
    ui_DeflectorBtn   = NULL;
    ui_DeflectorLabel = NULL;
    ui_WarpSlider     = NULL;
    ui_RedAlertBtn    = NULL;
    ui_YellowAlertBtn = NULL;

}
