// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: DataPad

#include "ui.h"

lv_obj_t * ui_Screen3 = NULL;
lv_obj_t * ui_Keyboard1 = NULL;
lv_obj_t * ui_TextArea1 = NULL;
lv_obj_t * ui_TextArea2 = NULL;
lv_obj_t * ui_Button2 = NULL;
lv_obj_t * ui_Label12 = NULL;
lv_obj_t * ui_Button3 = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_Label13 = NULL;
lv_obj_t * ui_Label14 = NULL;
lv_obj_t * ui_Button45 = NULL;
lv_obj_t * ui_Label16 = NULL;
lv_obj_t * ui_Button46 = NULL;
lv_obj_t * ui_Label17 = NULL;
lv_obj_t * ui_Label18 = NULL;
lv_obj_t * ui_Label19 = NULL;
lv_obj_t * ui_Label20 = NULL;
lv_obj_t * ui_Label21 = NULL;
lv_obj_t * ui_Button47 = NULL;
lv_obj_t * ui_Label15 = NULL;
lv_obj_t * ui_Label22 = NULL;
lv_obj_t * ui_Button50 = NULL;
lv_obj_t * ui_Label25 = NULL;
lv_obj_t * ui_WarpCoreStsBtn = NULL;
lv_obj_t * ui_LabelWCIP = NULL;
lv_obj_t * ui_LabelSaveHint = NULL;
// event funtions
void ui_event_TextArea1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_keyboard_set_target(ui_Keyboard1,  ui_TextArea1);
    }
}

void ui_event_TextArea2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_keyboard_set_target(ui_Keyboard1,  ui_TextArea2);
    }
}

void ui_event_Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen2_screen_init);
    }
}

void ui_event_Label12(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen1_screen_init);
    }
}

void ui_event_Button3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        StartWiFi(e);
    }
}

void ui_event_Label1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen1_screen_init);
    }
}

void ui_event_Label16(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen1_screen_init);
    }
}

void ui_event_Label17(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen1_screen_init);
    }
}

void ui_event_Button50(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        SaveWifi(e);
    }
}

void ui_event_Label25(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen1_screen_init);
    }
}

// build funtions

void ui_Screen3_screen_init(void)
{
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_set_style_border_color(ui_Screen3, lv_color_hex(0xFFFFFF), LV_PART_SCROLLBAR | LV_STATE_CHECKED);
    lv_obj_set_style_border_opa(ui_Screen3, 255, LV_PART_SCROLLBAR | LV_STATE_CHECKED);

    ui_Keyboard1 = lv_keyboard_create(ui_Screen3);
    lv_obj_set_width(ui_Keyboard1, 528);
    lv_obj_set_height(ui_Keyboard1, 215);
    lv_obj_set_x(ui_Keyboard1, -11);
    lv_obj_set_y(ui_Keyboard1, 130);
    lv_obj_set_align(ui_Keyboard1, LV_ALIGN_CENTER);

    lv_obj_set_style_bg_color(ui_Keyboard1, lv_color_hex(0x27209E), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Keyboard1, 255, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Keyboard1, LV_GRAD_DIR_VER, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Keyboard1, LV_GRAD_DIR_NONE, LV_PART_ITEMS | LV_STATE_CHECKED);
    lv_obj_set_style_border_color(ui_Keyboard1, lv_color_hex(0xFFFFFF), LV_PART_ITEMS | LV_STATE_PRESSED);
    lv_obj_set_style_border_opa(ui_Keyboard1, 255, LV_PART_ITEMS | LV_STATE_PRESSED);
    lv_obj_set_style_border_width(ui_Keyboard1, 5, LV_PART_ITEMS | LV_STATE_PRESSED);

    ui_TextArea1 = lv_textarea_create(ui_Screen3);
    lv_obj_set_width(ui_TextArea1, 230);
    lv_obj_set_height(ui_TextArea1, 40);
    lv_obj_set_x(ui_TextArea1, -121);
    lv_obj_set_y(ui_TextArea1, -55);
    lv_obj_set_align(ui_TextArea1, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_TextArea1, "enterprise");
    lv_textarea_set_placeholder_text(ui_TextArea1, "WiFi SSID");

    ui_TextArea2 = lv_textarea_create(ui_Screen3);
    lv_obj_set_width(ui_TextArea2, 230);
    lv_obj_set_height(ui_TextArea2, 40);
    lv_obj_set_x(ui_TextArea2, 124);
    lv_obj_set_y(ui_TextArea2, -55);
    lv_obj_set_align(ui_TextArea2, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_TextArea2, "ncc-1707-d");
    lv_textarea_set_placeholder_text(ui_TextArea2, "WiFi Password");

    ui_Button2 = lv_btn_create(ui_Screen3);
    lv_obj_set_width(ui_Button2, 102);
    lv_obj_set_height(ui_Button2, 42);
    lv_obj_set_x(ui_Button2, -318);
    lv_obj_set_y(ui_Button2, -43);
    lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button2, 700, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button2, lv_color_hex(0x2D802B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label12 = lv_label_create(ui_Button2);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, -3);
    lv_obj_set_y(ui_Label12, 1);
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "Go Back");
    lv_obj_set_style_text_color(ui_Label12, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label12, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button3 = lv_btn_create(ui_Screen3);
    lv_obj_set_width(ui_Button3, 102);
    lv_obj_set_height(ui_Button3, 42);
    lv_obj_set_x(ui_Button3, 318);
    lv_obj_set_y(ui_Button3, -40);
    lv_obj_set_align(ui_Button3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button3, 700, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button3, lv_color_hex(0xC41313), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_Button3);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -2);
    lv_obj_set_y(ui_Label1, 0);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Start Wifi");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label13 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label13, -16);
    lv_obj_set_y(ui_Label13, -149);
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13,
                      "Warning this is to set a WiFi SSID and Password \nso you can access a web GUI and Can do \nOTA Updates. If you Do an OTA Update make sure\nyou Program has and OTA Update program or will\nnot be able to update with Out Disassembly");

    ui_Label14 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label14, -18);
    lv_obj_set_y(ui_Label14, -213);
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "WARNING");
    lv_obj_set_style_text_color(ui_Label14, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_Label14, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label14, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button45 = lv_btn_create(ui_Screen3);
    lv_obj_set_width(ui_Button45, 102);
    lv_obj_set_height(ui_Button45, 42);
    lv_obj_set_x(ui_Button45, -318);
    lv_obj_set_y(ui_Button45, -190);
    lv_obj_set_align(ui_Button45, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button45, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button45, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button45, 700, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button45, lv_color_hex(0xC41313), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button45, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button45, lv_color_hex(0x2D802B), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Button45, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Label16 = lv_label_create(ui_Button45);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label16, -3);
    lv_obj_set_y(ui_Label16, 1);
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, "Batle Bridge\nStatus");
    lv_obj_set_style_text_color(ui_Label16, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label16, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label16, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button46 = lv_btn_create(ui_Screen3);
    lv_obj_set_width(ui_Button46, 102);
    lv_obj_set_height(ui_Button46, 42);
    lv_obj_set_x(ui_Button46, 318);
    lv_obj_set_y(ui_Button46, -190);
    lv_obj_set_align(ui_Button46, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button46, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button46, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button46, 700, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button46, lv_color_hex(0xC41313), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button46, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button46, lv_color_hex(0x2D802B), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Button46, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Label17 = lv_label_create(ui_Button46);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label17, -3);
    lv_obj_set_y(ui_Label17, 1);
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "Saucer\nStatus");
    lv_obj_set_style_text_color(ui_Label17, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label17, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label17, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WarpCoreStsBtn = lv_btn_create(ui_Screen3);
    lv_obj_set_width(ui_WarpCoreStsBtn, 102);
    lv_obj_set_height(ui_WarpCoreStsBtn, 42);
    lv_obj_set_x(ui_WarpCoreStsBtn, 318);
    lv_obj_set_y(ui_WarpCoreStsBtn, -115);
    lv_obj_set_align(ui_WarpCoreStsBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WarpCoreStsBtn, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);
    lv_obj_clear_flag(ui_WarpCoreStsBtn, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_radius(ui_WarpCoreStsBtn, 700, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_WarpCoreStsBtn, lv_color_hex(0xC41313), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WarpCoreStsBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_WarpCoreStsBtn, lv_color_hex(0x2D802B), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_WarpCoreStsBtn, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    lv_obj_t * ui_WCLbl = lv_label_create(ui_WarpCoreStsBtn);
    lv_obj_set_align(ui_WCLbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WCLbl, "WarpCore\nStatus");
    lv_obj_set_style_text_color(ui_WCLbl, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WCLbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_WCLbl, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WCLbl, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelWCIP = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_LabelWCIP, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_LabelWCIP, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_LabelWCIP, 318);
    lv_obj_set_y(ui_LabelWCIP, -72);
    lv_obj_set_align(ui_LabelWCIP, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelWCIP, "IP Address");

    ui_Label18 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label18, -318);
    lv_obj_set_y(ui_Label18, -147);
    lv_obj_set_align(ui_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label18, "IP Address");

    ui_Label19 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label19, 318);
    lv_obj_set_y(ui_Label19, -146);
    lv_obj_set_align(ui_Label19, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label19, "IP Address");

    ui_Label20 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label20, -131);
    lv_obj_set_y(ui_Label20, -87);
    lv_obj_set_align(ui_Label20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label20, "WiFi SSID");

    ui_Label21 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label21, 119);
    lv_obj_set_y(ui_Label21, -87);
    lv_obj_set_align(ui_Label21, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label21, "WiFi Password");

    ui_Button47 = lv_btn_create(ui_Screen3);
    lv_obj_set_width(ui_Button47, 167);
    lv_obj_set_height(ui_Button47, 40);
    lv_obj_set_x(ui_Button47, -5);
    lv_obj_set_y(ui_Button47, -4);
    lv_obj_set_align(ui_Button47, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button47, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button47, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button47, 700, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button47, lv_color_hex(0xC41313), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button47, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button47, lv_color_hex(0x2D802B), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Button47, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Label15 = lv_label_create(ui_Button47);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label15, 0);
    lv_obj_set_y(ui_Label15, 12);
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "IP Address");

    ui_Label22 = lv_label_create(ui_Button47);
    lv_obj_set_width(ui_Label22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label22, -2);
    lv_obj_set_y(ui_Label22, -8);
    lv_obj_set_align(ui_Label22, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label22, "Data Pad");
    lv_obj_set_style_text_color(ui_Label22, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label22, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label22, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button50 = lv_btn_create(ui_Screen3);
    lv_obj_set_width(ui_Button50, 102);
    lv_obj_set_height(ui_Button50, 42);
    lv_obj_set_x(ui_Button50, 318);
    lv_obj_set_y(ui_Button50, 12);
    lv_obj_set_align(ui_Button50, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button50, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button50, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button50, 700, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button50, lv_color_hex(0xC41313), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button50, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button50, lv_color_hex(0x2D802B), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Button50, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Label25 = lv_label_create(ui_Button50);
    lv_obj_set_width(ui_Label25, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label25, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label25, -2);
    lv_obj_set_y(ui_Label25, 0);
    lv_obj_set_align(ui_Label25, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label25, "Save Wifi");
    lv_obj_set_style_text_color(ui_Label25, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label25, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label25, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSaveHint = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_LabelSaveHint, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_LabelSaveHint, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_LabelSaveHint, 318);
    lv_obj_set_y(ui_LabelSaveHint, 48);
    lv_obj_set_align(ui_LabelSaveHint, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSaveHint, "");
    lv_obj_set_style_text_font(ui_LabelSaveHint, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelSaveHint, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_TextArea1, ui_event_TextArea1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextArea2, ui_event_TextArea2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Label12, ui_event_Label12, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button2, ui_event_Button2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Label1, ui_event_Label1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Label16, ui_event_Label16, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Label17, ui_event_Label17, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Label25, ui_event_Label25, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button50, ui_event_Button50, LV_EVENT_ALL, NULL);

    populateWifiFields();

}

void ui_Screen3_screen_destroy(void)
{
    if(ui_Screen3) lv_obj_del(ui_Screen3);

    // NULL screen variables
    ui_Screen3 = NULL;
    ui_Keyboard1 = NULL;
    ui_TextArea1 = NULL;
    ui_TextArea2 = NULL;
    ui_Button2 = NULL;
    ui_Label12 = NULL;
    ui_Button3 = NULL;
    ui_Label1 = NULL;
    ui_Label13 = NULL;
    ui_Label14 = NULL;
    ui_Button45 = NULL;
    ui_Label16 = NULL;
    ui_Button46 = NULL;
    ui_Label17 = NULL;
    ui_Label18 = NULL;
    ui_Label19 = NULL;
    ui_Label20 = NULL;
    ui_Label21 = NULL;
    ui_Button47 = NULL;
    ui_Label15 = NULL;
    ui_Label22 = NULL;
    ui_Button50 = NULL;
    ui_Label25 = NULL;
    ui_WarpCoreStsBtn = NULL;
    ui_LabelWCIP = NULL;
    ui_LabelSaveHint = NULL;

}
