// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: DataPad

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Button33;
extern lv_obj_t * ui_Button44;
extern lv_obj_t * ui_Button39;
extern lv_obj_t * ui_Button40;
extern lv_obj_t * ui_Button41;
extern void ui_event_Button38(lv_event_t * e);
extern lv_obj_t * ui_Button38;
extern lv_obj_t * ui_Button37;
extern lv_obj_t * ui_Button36;
extern void ui_event_Button35(lv_event_t * e);
extern lv_obj_t * ui_Button35;
extern lv_obj_t * ui_Button34;
extern lv_obj_t * ui_Button32;
extern lv_obj_t * ui_Button31;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Button30;
extern void ui_event_Button13(lv_event_t * e);
extern lv_obj_t * ui_Button13;
extern lv_obj_t * ui_Label2;
extern void ui_event_Button14(lv_event_t * e);
extern lv_obj_t * ui_Button14;
extern lv_obj_t * ui_Label5;
extern void ui_event_Button15(lv_event_t * e);
extern lv_obj_t * ui_Button15;
extern lv_obj_t * ui_Label6;
extern void ui_event_Button16(lv_event_t * e);
extern lv_obj_t * ui_Button16;
extern lv_obj_t * ui_Label4;
extern void ui_event_Button17(lv_event_t * e);
extern lv_obj_t * ui_Button17;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Button42;
extern lv_obj_t * ui_Button43;
extern lv_obj_t * ui_Label8;
extern void ui_event_Button48(lv_event_t * e);
extern lv_obj_t * ui_Button48;
extern lv_obj_t * ui_Label23;
extern void ui_event_Button49(lv_event_t * e);
extern lv_obj_t * ui_Button49;
extern lv_obj_t * ui_Label24;
extern void ui_event_Button51(lv_event_t * e);
extern lv_obj_t * ui_Button51;
extern lv_obj_t * ui_Label26;
extern void ui_event_DeflectorBtn(lv_event_t * e);
extern lv_obj_t * ui_DeflectorBtn;
extern lv_obj_t * ui_DeflectorLabel;
extern void ui_event_WarpSlider(lv_event_t * e);
extern lv_obj_t * ui_WarpSlider;
extern void ui_event_RedAlertBtn(lv_event_t * e);
extern lv_obj_t * ui_RedAlertBtn;
extern void ui_event_YellowAlertBtn(lv_event_t * e);
extern lv_obj_t * ui_YellowAlertBtn;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

